version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    groups:
      eslint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint*"
      i18next:
        patterns:
          - "i18next*"
      react:
        patterns:
          - "@types/react"
          - "@types/react-dom"
          - "react"
          - "react-dom"
      storybook:
        patterns:
          - "@storybook/*"
      stylelint:
        patterns:
          - "stylelint*"
      vite:
        patterns:
          - "@vitejs/*"
          - "@vitest/*"
          - "happy-dom"
          - "vite"
          - "vitest"